"""
Oversættelser til Fil-Organisator.
"""
import os, sys, json
import tkinter as tk

# ── Config ──────────────────────────────────────────
def _config_path():
    d = os.path.join(os.environ.get("APPDATA", os.path.expanduser("~")), "FilOrganisator")
    os.makedirs(d, exist_ok=True)
    return os.path.join(d, "config.json")

def load_config():
    try:
        with open(_config_path(), encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return {}

def save_config(cfg):
    try:
        with open(_config_path(), "w", encoding="utf-8") as f:
            json.dump(cfg, f)
    except Exception:
        pass

T = {}
_current_lang = "en"

def set_sprog(code):
    global T, _current_lang
    _current_lang = code
    T.clear()
    T.update(TEKSTER.get(code, TEKSTER["en"]))
    c = load_config()
    c["sprog"] = code
    save_config(c)

def init_sprog():
    c = load_config()
    lang = c.get("sprog")
    if lang and lang in TEKSTER:
        set_sprog(lang)
        return lang
    return None

SPROG_LISTE = [
    ("da", "🇩🇰  Dansk"),
    ("en", "🇬🇧  English"),
    ("zh", "🇨🇳  简体中文"),
    ("hi", "🇮🇳  हिन्दी"),
    ("es", "🇪🇸  Español"),
    ("fr", "🇫🇷  Français"),
    ("ar", "🇸🇦  العربية"),
    ("bn", "🇧🇩  বাংলা"),
    ("pt", "🇧🇷  Português"),
    ("ru", "🇷🇺  Русский"),
]

_BG = "#1e1e2e"
_PANEL = "#2a2a3e"
_ACCENT = "#7c6af7"
_TEKST = "#cdd6f4"

class SprogVælger(tk.Toplevel):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.valgt = None
        self.title("Choose Language")
        self.configure(bg=_BG)
        self.resizable(False, False)
        self.protocol("WM_DELETE_WINDOW", self._default)
        self.grab_set()
        tk.Label(self, text="🌐  Choose Language / Vælg sprog",
                 font=("Segoe UI", 16, "bold"), bg=_BG, fg="white",
                 pady=16).pack(fill="x")
        frame = tk.Frame(self, bg=_BG, padx=30, pady=10)
        frame.pack(fill="both", expand=True)
        for code, name in SPROG_LISTE:
            tk.Button(frame, text=name, font=("Segoe UI", 13),
                      bg=_PANEL, fg=_TEKST, relief="flat",
                      padx=20, pady=8, cursor="hand2", anchor="w",
                      activebackground=_ACCENT, activeforeground="white",
                      command=lambda c=code: self._vælg(c)
                      ).pack(fill="x", pady=2)
        tk.Label(self, text="", bg=_BG, pady=8).pack()
        self.update_idletasks()
        w, h = self.winfo_reqwidth(), self.winfo_reqheight()
        sw, sh = self.winfo_screenwidth(), self.winfo_screenheight()
        self.geometry(f"+{(sw-w)//2}+{(sh-h)//2}")

    def _vælg(self, code):
        self.valgt = code
        self.destroy()

    def _default(self):
        self.valgt = "en"
        self.destroy()

# ── Oversættelser ───────────────────────────────────
TEKSTER = {

"da": {
    "lang_btn": "Sprog",
    "app_title": "Fil-Organisator  v{}",
    "app_heading": "📂  Fil-Organisator",
    "app_sub": "USB-udgave  v{}  –  Organisér billeder, videoer og dokumenter",
    "btn_start": "▶  Start organisering",
    "btn_stop": "⏹  Stop",
    "btn_dupes": "🔍  Find dubletter",
    "btn_close": "✖  Luk",
    "btn_running": "⏳  Kører...",
    "btn_scanning": "⏳  Scanner...",
    "sec_search": "🔎  Hvad skal søges igennem?",
    "sec_type": "🗂️  Hvad skal organiseres?",
    "sec_progress": "⏳  Fremgang",
    "sec_log": "📋  Log",
    "search_drive": "  Søg på hele drevet",
    "search_folders": "  Vælg specifikke mapper",
    "lbl_drive": "💾  Vælg drev",
    "lbl_folders": "📁  Valgte mapper",
    "btn_add": "＋  Tilføj mappe",
    "btn_remove": "✖  Fjern valgt",
    "btn_clear": "🗑  Ryd alle",
    "no_folders": "  Ingen mapper valgt endnu  –  klik '＋ Tilføj mappe' for at vælge",
    "dlg_add_folder": "Vælg en mappe der skal søges i",
    "type_photos": "📷  Billeder",
    "type_videos": "🎬  Videoer",
    "type_docs": "📄  Dokumenter",
    "hint_photos": "→ Drev:\\Billeder\\År\\Måned\\",
    "hint_videos": "→ Drev:\\Film\\År\\Måned\\",
    "hint_docs": "→ Drev:\\Dokumenter\\Word|PDF|Excel\\",
    "sort_label": "  Sorter billeder efter:",
    "sort_date": "  📅  Dato  –  År / Måned",
    "sort_gps": "  🌍  GPS-lokation  –  Land / By",
    "sort_gps_hint": "     Kræver GPS-data i billedet (smartphones gemmer dette automatisk)",
    "dest_auto": "  Filerne flyttes til:  [Drev:]\\{}\\  (oprettes automatisk)",
    "dest_photos": "Billeder",
    "dest_videos": "Film",
    "dest_docs": "Dokumenter",
    "dest_gps": "Billeder efter lokation",
    "dlg_dest": "Vælg destinations-mappe",
    "status_ready": "Klar til at starte...",
    "status_done": "Færdig!",
    "status_scan_done": "Scanning færdig!",
    "dlg_no_folders_t": "Ingen mapper",
    "dlg_no_folders": "Du har ikke valgt nogen mapper endnu.\nKlik '+ Tilfoej mappe' for at vaelge mindst een mappe.",
    "dlg_confirm_t": "Bekræft",
    "dlg_confirm": "Filer FLYTTES fra:\n  {}\n\ntil:\n  {}\n\nHar du lavet en sikkerhedskopi?\nVil du fortsætte?",
    "log_no_pillow": "❌  Hverken Pillow eller exifread er installeret!",
    "log_scan_photos": "🔍  Scanner efter billedfiler...",
    "log_found_photos": "✅  Fandt {} billedfiler",
    "log_stopped": "⛔  Stoppet af bruger.",
    "log_moved_n": "  ✔  {} billeder flyttet...",
    "log_err": "  ✘ FEJL: {}: {}",
    "log_done": "  🏁  Faerdig!",
    "log_photos_moved": "  Billeder flyttet:     {}",
    "log_filedate": "  Brugte filens dato:   {}",
    "log_errors": "  Fejl:                 {}",
    "log_no_geocoder": "❌  reverse_geocoder er ikke installeret!",
    "log_install_geo": "   Kør:  py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  Scanner efter billedfiler med GPS-data...",
    "log_gps_moved": "  Billeder flyttet:  {}",
    "log_no_gps": "  Ingen GPS-data:    {}",
    "log_scan_videos": "🔍  Scanner efter videofiler...",
    "log_found_videos": "✅  Fandt {} videofiler",
    "log_video_done": "  🏁  Faerdig!  Videoer flyttet: {}  |  Fejl: {}",
    "log_scan_docs": "🔍  Scanner efter dokumenter...",
    "log_found_docs": "✅  Fandt {} dokumenter",
    "log_doc_done": "  Word:   {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  Fejl:   {}",
    "log_skipped": "  ⚠️  {} mapper sprunget over (system/spil-mapper)",
    "log_scan_files": "🔍  Scanner efter filer...",
    "log_found_files": "✅  Fandt {} filer",
    "log_grouping": "⚙️  Grupperer efter størrelse...",
    "log_candidates": "  {} kandidater videre til checksum-tjek",
    "log_no_dupes": "✅  Ingen dubletter fundet.",
    "log_checksums": "🔐  Beregner checksummer (kan tage lidt tid for store filer)...",
    "log_scan_complete": "  🏁  Scanning faerdig!",
    "log_dupe_groups": "  Dublet-grupper:  {}",
    "log_can_save": "  Kan spare:       {}",
    "log_search_in": "🔍  Søger efter dubletter i: {}",
    "log_search_folders": "📁  Søger i {} valgte mapper:",
    "dupe_title": "Dublet-scanner – Resultater",
    "dupe_header": "🔍  {} dublet-grupper  ·  {} ekstra kopier  ·  Kan spare {}",
    "dupe_stats": "  {} filer markeret til sletning  ·  {} frigøres",
    "dupe_col_file": "Filnavn",
    "dupe_col_folder": "Mappe",
    "dupe_col_size": "Størrelse",
    "dupe_col_date": "Dato",
    "dupe_group": "  📁  Gruppe {}  –  {} filer  –  kan spare {}",
    "dupe_btn_del": "🗑  Slet markerede til papirkurv",
    "dupe_btn_sel": "☑  Vælg alle dubletter",
    "dupe_btn_desel": "☐  Fravælg alle",
    "dupe_ready": "Klar",
    "dupe_deleting": "Sletter filer...",
    "dupe_trash_ok": "  ✔  Papirkurv: {}",
    "dupe_trash_fail": "  ✘  Fejl: {}",
    "dupe_del_done": "\n  🏁  Faerdig!  Slettet: {}  |  Fejl: {}",
    "dupe_done_lbl": "Færdig!",
    "dupe_none_t": "Ingen valgt",
    "dupe_none": "Ingen filer er markeret til sletning.",
    "dupe_confirm_t": "Bekræft sletning",
    "dupe_confirm": "{} filer flyttes til papirkurven.\nDet frigiver {}.\n\nFilerne kan gendannes fra papirkurven.\nVil du fortsætte?",
    "dupe_no_t": "Ingen dubletter",
    "dupe_no": "Ingen dubletter fundet i det valgte område.",
},

"en": {
    "lang_btn": "Language",
    "app_title": "File Organizer  v{}",
    "app_heading": "📂  File Organizer",
    "app_sub": "USB Edition  v{}  –  Organize photos, videos and documents",
    "btn_start": "▶  Start organizing",
    "btn_stop": "⏹  Stop",
    "btn_dupes": "🔍  Find duplicates",
    "btn_close": "✖  Close",
    "btn_running": "⏳  Running...",
    "btn_scanning": "⏳  Scanning...",
    "sec_search": "🔎  What to search?",
    "sec_type": "🗂️  What to organize?",
    "sec_progress": "⏳  Progress",
    "sec_log": "📋  Log",
    "search_drive": "  Search entire drive",
    "search_folders": "  Choose specific folders",
    "lbl_drive": "💾  Choose drive",
    "lbl_folders": "📁  Selected folders",
    "btn_add": "＋  Add folder",
    "btn_remove": "✖  Remove selected",
    "btn_clear": "🗑  Clear all",
    "no_folders": "  No folders selected yet – click '＋ Add folder' to choose",
    "dlg_add_folder": "Choose a folder to search",
    "type_photos": "📷  Photos",
    "type_videos": "🎬  Videos",
    "type_docs": "📄  Documents",
    "hint_photos": "→ Drive:\\Photos\\Year\\Month\\",
    "hint_videos": "→ Drive:\\Videos\\Year\\Month\\",
    "hint_docs": "→ Drive:\\Documents\\Word|PDF|Excel\\",
    "sort_label": "  Sort photos by:",
    "sort_date": "  📅  Date  –  Year / Month",
    "sort_gps": "  🌍  GPS Location  –  Country / City",
    "sort_gps_hint": "     Requires GPS data in image (smartphones save this automatically)",
    "dest_auto": "  Files will be moved to: [Drive:]\\{}\\  (created automatically)",
    "dest_photos": "Photos",
    "dest_videos": "Videos",
    "dest_docs": "Documents",
    "dest_gps": "Photos by location",
    "dlg_dest": "Choose destination folder",
    "status_ready": "Ready to start...",
    "status_done": "Done!",
    "status_scan_done": "Scan complete!",
    "dlg_no_folders_t": "No folders",
    "dlg_no_folders": "You haven't selected any folders yet.\nClick '+ Add folder' to select at least one.",
    "dlg_confirm_t": "Confirm",
    "dlg_confirm": "Files will be MOVED from:\n  {}\n\nto:\n  {}\n\nHave you made a backup?\nDo you want to continue?",
    "log_no_pillow": "❌  Neither Pillow nor exifread is installed!",
    "log_scan_photos": "🔍  Scanning for image files...",
    "log_found_photos": "✅  Found {} image files",
    "log_stopped": "⛔  Stopped by user.",
    "log_moved_n": "  ✔  {} images moved...",
    "log_err": "  ✘ ERROR: {}: {}",
    "log_done": "  🏁  Done!",
    "log_photos_moved": "  Images moved:       {}",
    "log_filedate": "  Used file date:     {}",
    "log_errors": "  Errors:             {}",
    "log_no_geocoder": "❌  reverse_geocoder is not installed!",
    "log_install_geo": "   Run:  py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  Scanning for images with GPS data...",
    "log_gps_moved": "  Images moved:  {}",
    "log_no_gps": "  No GPS data:   {}",
    "log_scan_videos": "🔍  Scanning for video files...",
    "log_found_videos": "✅  Found {} video files",
    "log_video_done": "  🏁  Done!  Videos moved: {}  |  Errors: {}",
    "log_scan_docs": "🔍  Scanning for documents...",
    "log_found_docs": "✅  Found {} documents",
    "log_doc_done": "  Word:   {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  Errors: {}",
    "log_skipped": "  ⚠️  {} folders skipped (system/game folders)",
    "log_scan_files": "🔍  Scanning for files...",
    "log_found_files": "✅  Found {} files",
    "log_grouping": "⚙️  Grouping by size...",
    "log_candidates": "  {} candidates for checksum verification",
    "log_no_dupes": "✅  No duplicates found.",
    "log_checksums": "🔐  Calculating checksums (may take a while for large files)...",
    "log_scan_complete": "  🏁  Scan complete!",
    "log_dupe_groups": "  Duplicate groups:  {}",
    "log_can_save": "  Can save:          {}",
    "log_search_in": "🔍  Searching for duplicates in: {}",
    "log_search_folders": "📁  Searching in {} selected folders:",
    "dupe_title": "Duplicate Scanner – Results",
    "dupe_header": "🔍  {} duplicate groups  ·  {} extra copies  ·  Can save {}",
    "dupe_stats": "  {} files marked for deletion  ·  {} will be freed",
    "dupe_col_file": "Filename",
    "dupe_col_folder": "Folder",
    "dupe_col_size": "Size",
    "dupe_col_date": "Date",
    "dupe_group": "  📁  Group {}  –  {} files  –  can save {}",
    "dupe_btn_del": "🗑  Delete selected to recycle bin",
    "dupe_btn_sel": "☑  Select all duplicates",
    "dupe_btn_desel": "☐  Deselect all",
    "dupe_ready": "Ready",
    "dupe_deleting": "Deleting files...",
    "dupe_trash_ok": "  ✔  Recycle bin: {}",
    "dupe_trash_fail": "  ✘  Error: {}",
    "dupe_del_done": "\n  🏁  Done!  Deleted: {}  |  Errors: {}",
    "dupe_done_lbl": "Done!",
    "dupe_none_t": "None selected",
    "dupe_none": "No files are marked for deletion.",
    "dupe_confirm_t": "Confirm deletion",
    "dupe_confirm": "{} files will be moved to the recycle bin.\nThis will free {}.\n\nFiles can be restored from the recycle bin.\nDo you want to continue?",
    "dupe_no_t": "No duplicates",
    "dupe_no": "No duplicates found in the selected area.",
},

"zh": {
    "lang_btn": "语言",
    "app_title": "文件整理器  v{}",
    "app_heading": "📂  文件整理器",
    "app_sub": "USB版  v{}  –  整理照片、视频和文档",
    "btn_start": "▶  开始整理",
    "btn_stop": "⏹  停止",
    "btn_dupes": "🔍  查找重复文件",
    "btn_close": "✖  关闭",
    "btn_running": "⏳  运行中...",
    "btn_scanning": "⏳  扫描中...",
    "sec_search": "🔎  搜索范围",
    "sec_type": "🗂️  整理类型",
    "sec_progress": "⏳  进度",
    "sec_log": "📋  日志",
    "search_drive": "  搜索整个驱动器",
    "search_folders": "  选择特定文件夹",
    "lbl_drive": "💾  选择驱动器",
    "lbl_folders": "📁  已选文件夹",
    "btn_add": "＋  添加文件夹",
    "btn_remove": "✖  移除所选",
    "btn_clear": "🗑  清空全部",
    "no_folders": "  尚未选择文件夹 – 点击 '＋ 添加文件夹' 进行选择",
    "dlg_add_folder": "选择要搜索的文件夹",
    "type_photos": "📷  照片",
    "type_videos": "🎬  视频",
    "type_docs": "📄  文档",
    "hint_photos": "→ 驱动器:\\照片\\年\\月\\",
    "hint_videos": "→ 驱动器:\\视频\\年\\月\\",
    "hint_docs": "→ 驱动器:\\文档\\Word|PDF|Excel\\",
    "sort_label": "  照片排序方式：",
    "sort_date": "  📅  日期  –  年 / 月",
    "sort_gps": "  🌍  GPS定位  –  国家 / 城市",
    "sort_gps_hint": "     需要照片中包含GPS数据（智能手机会自动保存）",
    "dest_auto": "  文件将移动到：[驱动器:]\\{}\\（自动创建）",
    "dest_photos": "照片",
    "dest_videos": "视频",
    "dest_docs": "文档",
    "dest_gps": "按地点分类的照片",
    "dlg_dest": "选择目标文件夹",
    "status_ready": "准备就绪...",
    "status_done": "完成！",
    "status_scan_done": "扫描完成！",
    "dlg_no_folders_t": "未选择文件夹",
    "dlg_no_folders": "您尚未选择任何文件夹。\n请点击 '＋ 添加文件夹' 至少选择一个。",
    "dlg_confirm_t": "确认",
    "dlg_confirm": "文件将从：\n  {}\n\n移动到：\n  {}\n\n是否已备份？\n是否继续？",
    "log_no_pillow": "❌  Pillow和exifread均未安装！",
    "log_scan_photos": "🔍  正在扫描图片文件...",
    "log_found_photos": "✅  找到 {} 个图片文件",
    "log_stopped": "⛔  已被用户停止。",
    "log_moved_n": "  ✔  已移动 {} 张图片...",
    "log_err": "  ✘ 错误：{}：{}",
    "log_done": "  🏁  完成！",
    "log_photos_moved": "  已移动图片：    {}",
    "log_filedate": "  使用文件日期：  {}",
    "log_errors": "  错误：          {}",
    "log_no_geocoder": "❌  未安装reverse_geocoder！",
    "log_install_geo": "   运行：py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  正在扫描含GPS数据的图片...",
    "log_gps_moved": "  已移动图片：{}",
    "log_no_gps": "  无GPS数据：  {}",
    "log_scan_videos": "🔍  正在扫描视频文件...",
    "log_found_videos": "✅  找到 {} 个视频文件",
    "log_video_done": "  🏁  完成！已移动视频：{}  |  错误：{}",
    "log_scan_docs": "🔍  正在扫描文档...",
    "log_found_docs": "✅  找到 {} 个文档",
    "log_doc_done": "  Word：{}  |  PDF：{}  |  Excel：{}",
    "log_doc_errors": "  错误：{}",
    "log_skipped": "  ⚠️  跳过 {} 个文件夹（系统/游戏文件夹）",
    "log_scan_files": "🔍  正在扫描文件...",
    "log_found_files": "✅  找到 {} 个文件",
    "log_grouping": "⚙️  按大小分组...",
    "log_candidates": "  {} 个候选文件需要校验",
    "log_no_dupes": "✅  未找到重复文件。",
    "log_checksums": "🔐  正在计算校验和（大文件可能需要一些时间）...",
    "log_scan_complete": "  🏁  扫描完成！",
    "log_dupe_groups": "  重复组：  {}",
    "log_can_save": "  可节省：  {}",
    "log_search_in": "🔍  正在搜索重复文件：{}",
    "log_search_folders": "📁  在 {} 个已选文件夹中搜索：",
    "dupe_title": "重复文件扫描器 – 结果",
    "dupe_header": "🔍  {} 个重复组  ·  {} 个额外副本  ·  可节省 {}",
    "dupe_stats": "  {} 个文件标记为删除  ·  可释放 {}",
    "dupe_col_file": "文件名",
    "dupe_col_folder": "文件夹",
    "dupe_col_size": "大小",
    "dupe_col_date": "日期",
    "dupe_group": "  📁  第{}组  –  {}个文件  –  可节省 {}",
    "dupe_btn_del": "🗑  删除所选到回收站",
    "dupe_btn_sel": "☑  全选重复文件",
    "dupe_btn_desel": "☐  取消全选",
    "dupe_ready": "就绪",
    "dupe_deleting": "正在删除文件...",
    "dupe_trash_ok": "  ✔  回收站：{}",
    "dupe_trash_fail": "  ✘  错误：{}",
    "dupe_del_done": "\n  🏁  完成！已删除：{}  |  错误：{}",
    "dupe_done_lbl": "完成！",
    "dupe_none_t": "未选择",
    "dupe_none": "没有文件被标记为删除。",
    "dupe_confirm_t": "确认删除",
    "dupe_confirm": "{} 个文件将移动到回收站。\n将释放 {}。\n\n文件可从回收站恢复。\n是否继续？",
    "dupe_no_t": "无重复文件",
    "dupe_no": "在所选区域未找到重复文件。",
},

"hi": {
    "lang_btn": "भाषा",
    "app_title": "फ़ाइल व्यवस्थापक  v{}",
    "app_heading": "📂  फ़ाइल व्यवस्थापक",
    "app_sub": "USB संस्करण  v{}  –  फ़ोटो, वीडियो और दस्तावेज़ व्यवस्थित करें",
    "btn_start": "▶  व्यवस्थित करें",
    "btn_stop": "⏹  रोकें",
    "btn_dupes": "🔍  डुप्लिकेट खोजें",
    "btn_close": "✖  बंद करें",
    "btn_running": "⏳  चल रहा है...",
    "btn_scanning": "⏳  स्कैन हो रहा है...",
    "sec_search": "🔎  कहाँ खोजें?",
    "sec_type": "🗂️  क्या व्यवस्थित करें?",
    "sec_progress": "⏳  प्रगति",
    "sec_log": "📋  लॉग",
    "search_drive": "  पूरी ड्राइव खोजें",
    "search_folders": "  विशिष्ट फ़ोल्डर चुनें",
    "lbl_drive": "💾  ड्राइव चुनें",
    "lbl_folders": "📁  चयनित फ़ोल्डर",
    "btn_add": "＋  फ़ोल्डर जोड़ें",
    "btn_remove": "✖  चयनित हटाएं",
    "btn_clear": "🗑  सब साफ़ करें",
    "no_folders": "  अभी तक कोई फ़ोल्डर नहीं चुना – '＋ फ़ोल्डर जोड़ें' पर क्लिक करें",
    "dlg_add_folder": "खोजने के लिए फ़ोल्डर चुनें",
    "type_photos": "📷  फ़ोटो",
    "type_videos": "🎬  वीडियो",
    "type_docs": "📄  दस्तावेज़",
    "hint_photos": "→ ड्राइव:\\फ़ोटो\\वर्ष\\महीना\\",
    "hint_videos": "→ ड्राइव:\\वीडियो\\वर्ष\\महीना\\",
    "hint_docs": "→ ड्राइव:\\दस्तावेज़\\Word|PDF|Excel\\",
    "sort_label": "  फ़ोटो क्रमबद्ध करें:",
    "sort_date": "  📅  तारीख  –  वर्ष / महीना",
    "sort_gps": "  🌍  GPS स्थान  –  देश / शहर",
    "sort_gps_hint": "     फ़ोटो में GPS डेटा आवश्यक (स्मार्टफ़ोन स्वतः सहेजते हैं)",
    "dest_auto": "  फ़ाइलें यहाँ जाएंगी: [ड्राइव:]\\{}\\  (स्वतः बनेगा)",
    "dest_photos": "Photos",
    "dest_videos": "Videos",
    "dest_docs": "Documents",
    "dest_gps": "Photos by location",
    "dlg_dest": "गंतव्य फ़ोल्डर चुनें",
    "status_ready": "शुरू करने के लिए तैयार...",
    "status_done": "पूर्ण!",
    "status_scan_done": "स्कैन पूर्ण!",
    "dlg_no_folders_t": "कोई फ़ोल्डर नहीं",
    "dlg_no_folders": "आपने अभी तक कोई फ़ोल्डर नहीं चुना।\n'+ फ़ोल्डर जोड़ें' पर क्लिक करें।",
    "dlg_confirm_t": "पुष्टि करें",
    "dlg_confirm": "फ़ाइलें यहाँ से:\n  {}\n\nयहाँ जाएंगी:\n  {}\n\nक्या आपने बैकअप लिया है?\nक्या जारी रखना चाहते हैं?",
    "log_no_pillow": "❌  Pillow और exifread दोनों स्थापित नहीं हैं!",
    "log_scan_photos": "🔍  छवि फ़ाइलें स्कैन हो रही हैं...",
    "log_found_photos": "✅  {} छवि फ़ाइलें मिलीं",
    "log_stopped": "⛔  उपयोगकर्ता द्वारा रोका गया।",
    "log_moved_n": "  ✔  {} छवियाँ स्थानांतरित...",
    "log_err": "  ✘ त्रुटि: {}: {}",
    "log_done": "  🏁  पूर्ण!",
    "log_photos_moved": "  छवियाँ स्थानांतरित:  {}",
    "log_filedate": "  फ़ाइल तारीख उपयोग: {}",
    "log_errors": "  त्रुटियाँ:          {}",
    "log_no_geocoder": "❌  reverse_geocoder स्थापित नहीं है!",
    "log_install_geo": "   चलाएं: py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  GPS डेटा वाली छवियाँ स्कैन हो रही हैं...",
    "log_gps_moved": "  छवियाँ स्थानांतरित: {}",
    "log_no_gps": "  GPS डेटा नहीं:    {}",
    "log_scan_videos": "🔍  वीडियो फ़ाइलें स्कैन हो रही हैं...",
    "log_found_videos": "✅  {} वीडियो फ़ाइलें मिलीं",
    "log_video_done": "  🏁  पूर्ण!  वीडियो: {}  |  त्रुटियाँ: {}",
    "log_scan_docs": "🔍  दस्तावेज़ स्कैन हो रहे हैं...",
    "log_found_docs": "✅  {} दस्तावेज़ मिले",
    "log_doc_done": "  Word: {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  त्रुटियाँ: {}",
    "log_skipped": "  ⚠️  {} फ़ोल्डर छोड़े गए (सिस्टम/गेम)",
    "log_scan_files": "🔍  फ़ाइलें स्कैन हो रही हैं...",
    "log_found_files": "✅  {} फ़ाइलें मिलीं",
    "log_grouping": "⚙️  आकार के अनुसार समूहीकरण...",
    "log_candidates": "  {} उम्मीदवार चेकसम सत्यापन के लिए",
    "log_no_dupes": "✅  कोई डुप्लिकेट नहीं मिला।",
    "log_checksums": "🔐  चेकसम गणना हो रही है (बड़ी फ़ाइलों में समय लग सकता है)...",
    "log_scan_complete": "  🏁  स्कैन पूर्ण!",
    "log_dupe_groups": "  डुप्लिकेट समूह: {}",
    "log_can_save": "  बचत:           {}",
    "log_search_in": "🔍  डुप्लिकेट खोज रहे हैं: {}",
    "log_search_folders": "📁  {} चयनित फ़ोल्डर में खोज:",
    "dupe_title": "डुप्लिकेट स्कैनर – परिणाम",
    "dupe_header": "🔍  {} डुप्लिकेट समूह  ·  {} अतिरिक्त प्रतियाँ  ·  बचत {}",
    "dupe_stats": "  {} फ़ाइलें हटाने के लिए चिह्नित  ·  {} मुक्त होगा",
    "dupe_col_file": "फ़ाइल नाम",
    "dupe_col_folder": "फ़ोल्डर",
    "dupe_col_size": "आकार",
    "dupe_col_date": "तारीख",
    "dupe_group": "  📁  समूह {}  –  {} फ़ाइलें  –  बचत {}",
    "dupe_btn_del": "🗑  चयनित हटाएं",
    "dupe_btn_sel": "☑  सभी डुप्लिकेट चुनें",
    "dupe_btn_desel": "☐  सभी अचयनित करें",
    "dupe_ready": "तैयार",
    "dupe_deleting": "फ़ाइलें हटाई जा रही हैं...",
    "dupe_trash_ok": "  ✔  रीसायकल बिन: {}",
    "dupe_trash_fail": "  ✘  त्रुटि: {}",
    "dupe_del_done": "\n  🏁  पूर्ण!  हटाई गई: {}  |  त्रुटियाँ: {}",
    "dupe_done_lbl": "पूर्ण!",
    "dupe_none_t": "कुछ चयनित नहीं",
    "dupe_none": "हटाने के लिए कोई फ़ाइल चिह्नित नहीं है।",
    "dupe_confirm_t": "हटाने की पुष्टि",
    "dupe_confirm": "{} फ़ाइलें रीसायकल बिन में जाएंगी।\n{} मुक्त होगा।\n\nफ़ाइलें पुनर्स्थापित की जा सकती हैं।\nजारी रखें?",
    "dupe_no_t": "कोई डुप्लिकेट नहीं",
    "dupe_no": "चयनित क्षेत्र में कोई डुप्लिकेट नहीं मिला।",
},

"es": {
    "lang_btn": "Idioma",
    "app_title": "Organizador de Archivos  v{}",
    "app_heading": "📂  Organizador de Archivos",
    "app_sub": "Edición USB  v{}  –  Organiza fotos, vídeos y documentos",
    "btn_start": "▶  Iniciar",
    "btn_stop": "⏹  Detener",
    "btn_dupes": "🔍  Buscar duplicados",
    "btn_close": "✖  Cerrar",
    "btn_running": "⏳  Ejecutando...",
    "btn_scanning": "⏳  Escaneando...",
    "sec_search": "🔎  ¿Dónde buscar?",
    "sec_type": "🗂️  ¿Qué organizar?",
    "sec_progress": "⏳  Progreso",
    "sec_log": "📋  Registro",
    "search_drive": "  Buscar en toda la unidad",
    "search_folders": "  Elegir carpetas específicas",
    "lbl_drive": "💾  Elegir unidad",
    "lbl_folders": "📁  Carpetas seleccionadas",
    "btn_add": "＋  Añadir carpeta",
    "btn_remove": "✖  Eliminar selección",
    "btn_clear": "🗑  Borrar todo",
    "no_folders": "  No hay carpetas seleccionadas – haz clic en '＋ Añadir carpeta'",
    "dlg_add_folder": "Elige una carpeta para buscar",
    "type_photos": "📷  Fotos",
    "type_videos": "🎬  Vídeos",
    "type_docs": "📄  Documentos",
    "hint_photos": "→ Unidad:\\Fotos\\Año\\Mes\\",
    "hint_videos": "→ Unidad:\\Vídeos\\Año\\Mes\\",
    "hint_docs": "→ Unidad:\\Documentos\\Word|PDF|Excel\\",
    "sort_label": "  Ordenar fotos por:",
    "sort_date": "  📅  Fecha  –  Año / Mes",
    "sort_gps": "  🌍  Ubicación GPS  –  País / Ciudad",
    "sort_gps_hint": "     Requiere datos GPS en la imagen (los smartphones los guardan automáticamente)",
    "dest_auto": "  Los archivos se moverán a: [Unidad:]\\{}\\  (se crea automáticamente)",
    "dest_photos": "Fotos",
    "dest_videos": "Videos",
    "dest_docs": "Documentos",
    "dest_gps": "Fotos por ubicación",
    "dlg_dest": "Elegir carpeta de destino",
    "status_ready": "Listo para empezar...",
    "status_done": "¡Hecho!",
    "status_scan_done": "¡Escaneo completo!",
    "dlg_no_folders_t": "Sin carpetas",
    "dlg_no_folders": "No has seleccionado ninguna carpeta.\nHaz clic en '+ Añadir carpeta' para seleccionar al menos una.",
    "dlg_confirm_t": "Confirmar",
    "dlg_confirm": "Los archivos se MOVERÁN de:\n  {}\n\na:\n  {}\n\n¿Has hecho una copia de seguridad?\n¿Deseas continuar?",
    "log_no_pillow": "❌  ¡Ni Pillow ni exifread están instalados!",
    "log_scan_photos": "🔍  Buscando archivos de imagen...",
    "log_found_photos": "✅  {} archivos de imagen encontrados",
    "log_stopped": "⛔  Detenido por el usuario.",
    "log_moved_n": "  ✔  {} imágenes movidas...",
    "log_err": "  ✘ ERROR: {}: {}",
    "log_done": "  🏁  ¡Hecho!",
    "log_photos_moved": "  Imágenes movidas:   {}",
    "log_filedate": "  Fecha de archivo:   {}",
    "log_errors": "  Errores:            {}",
    "log_no_geocoder": "❌  ¡reverse_geocoder no está instalado!",
    "log_install_geo": "   Ejecuta: py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  Buscando imágenes con datos GPS...",
    "log_gps_moved": "  Imágenes movidas: {}",
    "log_no_gps": "  Sin datos GPS:    {}",
    "log_scan_videos": "🔍  Buscando archivos de vídeo...",
    "log_found_videos": "✅  {} archivos de vídeo encontrados",
    "log_video_done": "  🏁  ¡Hecho!  Vídeos: {}  |  Errores: {}",
    "log_scan_docs": "🔍  Buscando documentos...",
    "log_found_docs": "✅  {} documentos encontrados",
    "log_doc_done": "  Word: {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  Errores: {}",
    "log_skipped": "  ⚠️  {} carpetas omitidas (sistema/juegos)",
    "log_scan_files": "🔍  Buscando archivos...",
    "log_found_files": "✅  {} archivos encontrados",
    "log_grouping": "⚙️  Agrupando por tamaño...",
    "log_candidates": "  {} candidatos para verificación",
    "log_no_dupes": "✅  No se encontraron duplicados.",
    "log_checksums": "🔐  Calculando checksums (puede tardar con archivos grandes)...",
    "log_scan_complete": "  🏁  ¡Escaneo completo!",
    "log_dupe_groups": "  Grupos duplicados: {}",
    "log_can_save": "  Ahorro posible:    {}",
    "log_search_in": "🔍  Buscando duplicados en: {}",
    "log_search_folders": "📁  Buscando en {} carpetas seleccionadas:",
    "dupe_title": "Escáner de Duplicados – Resultados",
    "dupe_header": "🔍  {} grupos  ·  {} copias extra  ·  Ahorro {}",
    "dupe_stats": "  {} archivos marcados para eliminar  ·  {} se liberará",
    "dupe_col_file": "Archivo",
    "dupe_col_folder": "Carpeta",
    "dupe_col_size": "Tamaño",
    "dupe_col_date": "Fecha",
    "dupe_group": "  📁  Grupo {}  –  {} archivos  –  ahorro {}",
    "dupe_btn_del": "🗑  Eliminar a papelera",
    "dupe_btn_sel": "☑  Seleccionar todos",
    "dupe_btn_desel": "☐  Deseleccionar todos",
    "dupe_ready": "Listo",
    "dupe_deleting": "Eliminando archivos...",
    "dupe_trash_ok": "  ✔  Papelera: {}",
    "dupe_trash_fail": "  ✘  Error: {}",
    "dupe_del_done": "\n  🏁  ¡Hecho!  Eliminados: {}  |  Errores: {}",
    "dupe_done_lbl": "¡Hecho!",
    "dupe_none_t": "Nada seleccionado",
    "dupe_none": "No hay archivos marcados para eliminar.",
    "dupe_confirm_t": "Confirmar eliminación",
    "dupe_confirm": "{} archivos se moverán a la papelera.\nSe liberará {}.\n\nLos archivos se pueden restaurar.\n¿Deseas continuar?",
    "dupe_no_t": "Sin duplicados",
    "dupe_no": "No se encontraron duplicados en el área seleccionada.",
},

"fr": {
    "lang_btn": "Langue",
    "app_title": "Organisateur de Fichiers  v{}",
    "app_heading": "📂  Organisateur de Fichiers",
    "app_sub": "Édition USB  v{}  –  Organisez photos, vidéos et documents",
    "btn_start": "▶  Démarrer",
    "btn_stop": "⏹  Arrêter",
    "btn_dupes": "🔍  Trouver les doublons",
    "btn_close": "✖  Fermer",
    "btn_running": "⏳  En cours...",
    "btn_scanning": "⏳  Analyse en cours...",
    "sec_search": "🔎  Où chercher ?",
    "sec_type": "🗂️  Quoi organiser ?",
    "sec_progress": "⏳  Progression",
    "sec_log": "📋  Journal",
    "search_drive": "  Chercher sur tout le disque",
    "search_folders": "  Choisir des dossiers spécifiques",
    "lbl_drive": "💾  Choisir le disque",
    "lbl_folders": "📁  Dossiers sélectionnés",
    "btn_add": "＋  Ajouter un dossier",
    "btn_remove": "✖  Supprimer la sélection",
    "btn_clear": "🗑  Tout effacer",
    "no_folders": "  Aucun dossier sélectionné – cliquez sur '＋ Ajouter un dossier'",
    "dlg_add_folder": "Choisir un dossier à analyser",
    "type_photos": "📷  Photos",
    "type_videos": "🎬  Vidéos",
    "type_docs": "📄  Documents",
    "hint_photos": "→ Disque:\\Photos\\Année\\Mois\\",
    "hint_videos": "→ Disque:\\Vidéos\\Année\\Mois\\",
    "hint_docs": "→ Disque:\\Documents\\Word|PDF|Excel\\",
    "sort_label": "  Trier les photos par :",
    "sort_date": "  📅  Date  –  Année / Mois",
    "sort_gps": "  🌍  Position GPS  –  Pays / Ville",
    "sort_gps_hint": "     Nécessite des données GPS dans l'image (les smartphones les enregistrent automatiquement)",
    "dest_auto": "  Les fichiers seront déplacés vers : [Disque:]\\{}\\  (créé automatiquement)",
    "dest_photos": "Photos",
    "dest_videos": "Vidéos",
    "dest_docs": "Documents",
    "dest_gps": "Photos par lieu",
    "dlg_dest": "Choisir le dossier de destination",
    "status_ready": "Prêt à démarrer...",
    "status_done": "Terminé !",
    "status_scan_done": "Analyse terminée !",
    "dlg_no_folders_t": "Aucun dossier",
    "dlg_no_folders": "Vous n'avez pas encore sélectionné de dossier.\nCliquez sur '+ Ajouter un dossier' pour en sélectionner au moins un.",
    "dlg_confirm_t": "Confirmer",
    "dlg_confirm": "Les fichiers seront DÉPLACÉS de :\n  {}\n\nvers :\n  {}\n\nAvez-vous fait une sauvegarde ?\nVoulez-vous continuer ?",
    "log_no_pillow": "❌  Ni Pillow ni exifread ne sont installés !",
    "log_scan_photos": "🔍  Recherche de fichiers image...",
    "log_found_photos": "✅  {} fichiers image trouvés",
    "log_stopped": "⛔  Arrêté par l'utilisateur.",
    "log_moved_n": "  ✔  {} images déplacées...",
    "log_err": "  ✘ ERREUR : {} : {}",
    "log_done": "  🏁  Terminé !",
    "log_photos_moved": "  Images déplacées :  {}",
    "log_filedate": "  Date du fichier :   {}",
    "log_errors": "  Erreurs :           {}",
    "log_no_geocoder": "❌  reverse_geocoder n'est pas installé !",
    "log_install_geo": "   Exécutez : py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  Recherche d'images avec données GPS...",
    "log_gps_moved": "  Images déplacées : {}",
    "log_no_gps": "  Pas de GPS :       {}",
    "log_scan_videos": "🔍  Recherche de fichiers vidéo...",
    "log_found_videos": "✅  {} fichiers vidéo trouvés",
    "log_video_done": "  🏁  Terminé !  Vidéos : {}  |  Erreurs : {}",
    "log_scan_docs": "🔍  Recherche de documents...",
    "log_found_docs": "✅  {} documents trouvés",
    "log_doc_done": "  Word : {}  |  PDF : {}  |  Excel : {}",
    "log_doc_errors": "  Erreurs : {}",
    "log_skipped": "  ⚠️  {} dossiers ignorés (système/jeux)",
    "log_scan_files": "🔍  Recherche de fichiers...",
    "log_found_files": "✅  {} fichiers trouvés",
    "log_grouping": "⚙️  Regroupement par taille...",
    "log_candidates": "  {} candidats à vérifier",
    "log_no_dupes": "✅  Aucun doublon trouvé.",
    "log_checksums": "🔐  Calcul des checksums (peut prendre du temps pour les gros fichiers)...",
    "log_scan_complete": "  🏁  Analyse terminée !",
    "log_dupe_groups": "  Groupes de doublons : {}",
    "log_can_save": "  Économie possible :  {}",
    "log_search_in": "🔍  Recherche de doublons dans : {}",
    "log_search_folders": "📁  Recherche dans {} dossiers sélectionnés :",
    "dupe_title": "Scanner de Doublons – Résultats",
    "dupe_header": "🔍  {} groupes  ·  {} copies supplémentaires  ·  Économie {}",
    "dupe_stats": "  {} fichiers marqués pour suppression  ·  {} libérés",
    "dupe_col_file": "Fichier",
    "dupe_col_folder": "Dossier",
    "dupe_col_size": "Taille",
    "dupe_col_date": "Date",
    "dupe_group": "  📁  Groupe {}  –  {} fichiers  –  économie {}",
    "dupe_btn_del": "🗑  Supprimer vers la corbeille",
    "dupe_btn_sel": "☑  Tout sélectionner",
    "dupe_btn_desel": "☐  Tout désélectionner",
    "dupe_ready": "Prêt",
    "dupe_deleting": "Suppression en cours...",
    "dupe_trash_ok": "  ✔  Corbeille : {}",
    "dupe_trash_fail": "  ✘  Erreur : {}",
    "dupe_del_done": "\n  🏁  Terminé !  Supprimés : {}  |  Erreurs : {}",
    "dupe_done_lbl": "Terminé !",
    "dupe_none_t": "Aucune sélection",
    "dupe_none": "Aucun fichier n'est marqué pour suppression.",
    "dupe_confirm_t": "Confirmer la suppression",
    "dupe_confirm": "{} fichiers seront déplacés vers la corbeille.\nCela libérera {}.\n\nLes fichiers peuvent être restaurés.\nVoulez-vous continuer ?",
    "dupe_no_t": "Pas de doublons",
    "dupe_no": "Aucun doublon trouvé dans la zone sélectionnée.",
},

"ar": {
    "lang_btn": "اللغة",
    "app_title": "منظم الملفات  v{}",
    "app_heading": "📂  منظم الملفات",
    "app_sub": "إصدار USB  v{}  –  تنظيم الصور والفيديو والمستندات",
    "btn_start": "▶  بدء التنظيم",
    "btn_stop": "⏹  إيقاف",
    "btn_dupes": "🔍  البحث عن التكرارات",
    "btn_close": "✖  إغلاق",
    "btn_running": "⏳  جاري التشغيل...",
    "btn_scanning": "⏳  جاري الفحص...",
    "sec_search": "🔎  أين تبحث؟",
    "sec_type": "🗂️  ماذا تنظم؟",
    "sec_progress": "⏳  التقدم",
    "sec_log": "📋  السجل",
    "search_drive": "  البحث في القرص بالكامل",
    "search_folders": "  اختيار مجلدات محددة",
    "lbl_drive": "💾  اختر القرص",
    "lbl_folders": "📁  المجلدات المحددة",
    "btn_add": "＋  إضافة مجلد",
    "btn_remove": "✖  إزالة المحدد",
    "btn_clear": "🗑  مسح الكل",
    "no_folders": "  لم يتم اختيار مجلدات بعد – انقر '＋ إضافة مجلد'",
    "dlg_add_folder": "اختر مجلداً للبحث فيه",
    "type_photos": "📷  صور",
    "type_videos": "🎬  فيديو",
    "type_docs": "📄  مستندات",
    "hint_photos": "→ القرص:\\صور\\سنة\\شهر\\",
    "hint_videos": "→ القرص:\\فيديو\\سنة\\شهر\\",
    "hint_docs": "→ القرص:\\مستندات\\Word|PDF|Excel\\",
    "sort_label": "  ترتيب الصور حسب:",
    "sort_date": "  📅  التاريخ  –  سنة / شهر",
    "sort_gps": "  🌍  موقع GPS  –  بلد / مدينة",
    "sort_gps_hint": "     يتطلب بيانات GPS في الصورة (الهواتف الذكية تحفظها تلقائياً)",
    "dest_auto": "  سيتم نقل الملفات إلى: [القرص:]\\{}\\  (يُنشأ تلقائياً)",
    "dest_photos": "Photos",
    "dest_videos": "Videos",
    "dest_docs": "Documents",
    "dest_gps": "Photos by location",
    "dlg_dest": "اختر مجلد الوجهة",
    "status_ready": "جاهز للبدء...",
    "status_done": "تم!",
    "status_scan_done": "اكتمل الفحص!",
    "dlg_no_folders_t": "لا مجلدات",
    "dlg_no_folders": "لم تختر أي مجلدات بعد.\nانقر '+ إضافة مجلد' لاختيار مجلد واحد على الأقل.",
    "dlg_confirm_t": "تأكيد",
    "dlg_confirm": "سيتم نقل الملفات من:\n  {}\n\nإلى:\n  {}\n\nهل قمت بعمل نسخة احتياطية؟\nهل تريد المتابعة؟",
    "log_no_pillow": "❌  لم يتم تثبيت Pillow أو exifread!",
    "log_scan_photos": "🔍  جاري البحث عن ملفات الصور...",
    "log_found_photos": "✅  تم العثور على {} ملف صورة",
    "log_stopped": "⛔  تم الإيقاف بواسطة المستخدم.",
    "log_moved_n": "  ✔  تم نقل {} صورة...",
    "log_err": "  ✘ خطأ: {}: {}",
    "log_done": "  🏁  تم!",
    "log_photos_moved": "  الصور المنقولة:    {}",
    "log_filedate": "  تاريخ الملف:      {}",
    "log_errors": "  الأخطاء:          {}",
    "log_no_geocoder": "❌  لم يتم تثبيت reverse_geocoder!",
    "log_install_geo": "   شغّل: py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  جاري البحث عن صور مع بيانات GPS...",
    "log_gps_moved": "  الصور المنقولة: {}",
    "log_no_gps": "  بدون GPS:      {}",
    "log_scan_videos": "🔍  جاري البحث عن ملفات الفيديو...",
    "log_found_videos": "✅  تم العثور على {} ملف فيديو",
    "log_video_done": "  🏁  تم!  فيديو: {}  |  أخطاء: {}",
    "log_scan_docs": "🔍  جاري البحث عن المستندات...",
    "log_found_docs": "✅  تم العثور على {} مستند",
    "log_doc_done": "  Word: {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  أخطاء: {}",
    "log_skipped": "  ⚠️  تم تجاوز {} مجلد (نظام/ألعاب)",
    "log_scan_files": "🔍  جاري البحث عن الملفات...",
    "log_found_files": "✅  تم العثور على {} ملف",
    "log_grouping": "⚙️  التجميع حسب الحجم...",
    "log_candidates": "  {} مرشح للتحقق",
    "log_no_dupes": "✅  لم يتم العثور على تكرارات.",
    "log_checksums": "🔐  جاري حساب المجاميع (قد يستغرق وقتاً للملفات الكبيرة)...",
    "log_scan_complete": "  🏁  اكتمل الفحص!",
    "log_dupe_groups": "  مجموعات مكررة: {}",
    "log_can_save": "  يمكن توفير:     {}",
    "log_search_in": "🔍  البحث عن تكرارات في: {}",
    "log_search_folders": "📁  البحث في {} مجلد محدد:",
    "dupe_title": "ماسح التكرارات – النتائج",
    "dupe_header": "🔍  {} مجموعة  ·  {} نسخة إضافية  ·  توفير {}",
    "dupe_stats": "  {} ملف محدد للحذف  ·  {} سيتم تحريره",
    "dupe_col_file": "اسم الملف",
    "dupe_col_folder": "المجلد",
    "dupe_col_size": "الحجم",
    "dupe_col_date": "التاريخ",
    "dupe_group": "  📁  مجموعة {}  –  {} ملفات  –  توفير {}",
    "dupe_btn_del": "🗑  حذف إلى سلة المحذوفات",
    "dupe_btn_sel": "☑  تحديد الكل",
    "dupe_btn_desel": "☐  إلغاء تحديد الكل",
    "dupe_ready": "جاهز",
    "dupe_deleting": "جاري حذف الملفات...",
    "dupe_trash_ok": "  ✔  سلة المحذوفات: {}",
    "dupe_trash_fail": "  ✘  خطأ: {}",
    "dupe_del_done": "\n  🏁  تم!  محذوف: {}  |  أخطاء: {}",
    "dupe_done_lbl": "تم!",
    "dupe_none_t": "لا شيء محدد",
    "dupe_none": "لم يتم تحديد أي ملفات للحذف.",
    "dupe_confirm_t": "تأكيد الحذف",
    "dupe_confirm": "سيتم نقل {} ملف إلى سلة المحذوفات.\nسيتم تحرير {}.\n\nيمكن استعادة الملفات.\nهل تريد المتابعة؟",
    "dupe_no_t": "لا تكرارات",
    "dupe_no": "لم يتم العثور على تكرارات في المنطقة المحددة.",
},

"bn": {
    "lang_btn": "ভাষা",
    "app_title": "ফাইল সংগঠক  v{}",
    "app_heading": "📂  ফাইল সংগঠক",
    "app_sub": "USB সংস্করণ  v{}  –  ছবি, ভিডিও ও নথি সংগঠিত করুন",
    "btn_start": "▶  শুরু করুন",
    "btn_stop": "⏹  থামান",
    "btn_dupes": "🔍  ডুপ্লিকেট খুঁজুন",
    "btn_close": "✖  বন্ধ",
    "btn_running": "⏳  চলছে...",
    "btn_scanning": "⏳  স্ক্যান হচ্ছে...",
    "sec_search": "🔎  কোথায় খুঁজবেন?",
    "sec_type": "🗂️  কী সংগঠিত করবেন?",
    "sec_progress": "⏳  অগ্রগতি",
    "sec_log": "📋  লগ",
    "search_drive": "  সম্পূর্ণ ড্রাইভে খুঁজুন",
    "search_folders": "  নির্দিষ্ট ফোল্ডার বেছে নিন",
    "lbl_drive": "💾  ড্রাইভ বেছে নিন",
    "lbl_folders": "📁  নির্বাচিত ফোল্ডার",
    "btn_add": "＋  ফোল্ডার যোগ করুন",
    "btn_remove": "✖  নির্বাচিত সরান",
    "btn_clear": "🗑  সব মুছুন",
    "no_folders": "  কোনো ফোল্ডার নির্বাচন করা হয়নি – '＋ ফোল্ডার যোগ করুন' ক্লিক করুন",
    "dlg_add_folder": "অনুসন্ধানের জন্য ফোল্ডার বেছে নিন",
    "type_photos": "📷  ছবি",
    "type_videos": "🎬  ভিডিও",
    "type_docs": "📄  নথি",
    "hint_photos": "→ ড্রাইভ:\\ছবি\\বছর\\মাস\\",
    "hint_videos": "→ ড্রাইভ:\\ভিডিও\\বছর\\মাস\\",
    "hint_docs": "→ ড্রাইভ:\\নথি\\Word|PDF|Excel\\",
    "sort_label": "  ছবি সাজান:",
    "sort_date": "  📅  তারিখ  –  বছর / মাস",
    "sort_gps": "  🌍  GPS অবস্থান  –  দেশ / শহর",
    "sort_gps_hint": "     ছবিতে GPS ডেটা প্রয়োজন (স্মার্টফোন স্বয়ংক্রিয়ভাবে সংরক্ষণ করে)",
    "dest_auto": "  ফাইল স্থানান্তরিত হবে: [ড্রাইভ:]\\{}\\  (স্বয়ংক্রিয়ভাবে তৈরি)",
    "dest_photos": "Photos",
    "dest_videos": "Videos",
    "dest_docs": "Documents",
    "dest_gps": "Photos by location",
    "dlg_dest": "গন্তব্য ফোল্ডার বেছে নিন",
    "status_ready": "শুরু করতে প্রস্তুত...",
    "status_done": "সম্পন্ন!",
    "status_scan_done": "স্ক্যান সম্পন্ন!",
    "dlg_no_folders_t": "কোনো ফোল্ডার নেই",
    "dlg_no_folders": "আপনি এখনো কোনো ফোল্ডার নির্বাচন করেননি।\n'+ ফোল্ডার যোগ করুন' ক্লিক করুন।",
    "dlg_confirm_t": "নিশ্চিত করুন",
    "dlg_confirm": "ফাইল স্থানান্তরিত হবে:\n  {}\n\nএখানে:\n  {}\n\nব্যাকআপ নিয়েছেন?\nচালিয়ে যেতে চান?",
    "log_no_pillow": "❌  Pillow বা exifread ইনস্টল নেই!",
    "log_scan_photos": "🔍  ছবি ফাইল খোঁজা হচ্ছে...",
    "log_found_photos": "✅  {} টি ছবি ফাইল পাওয়া গেছে",
    "log_stopped": "⛔  ব্যবহারকারী থামিয়েছেন।",
    "log_moved_n": "  ✔  {} টি ছবি স্থানান্তরিত...",
    "log_err": "  ✘ ত্রুটি: {}: {}",
    "log_done": "  🏁  সম্পন্ন!",
    "log_photos_moved": "  ছবি স্থানান্তরিত:  {}",
    "log_filedate": "  ফাইলের তারিখ:    {}",
    "log_errors": "  ত্রুটি:           {}",
    "log_no_geocoder": "❌  reverse_geocoder ইনস্টল নেই!",
    "log_install_geo": "   চালান: py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  GPS ডেটাসহ ছবি খোঁজা হচ্ছে...",
    "log_gps_moved": "  ছবি স্থানান্তরিত: {}",
    "log_no_gps": "  GPS ডেটা নেই:   {}",
    "log_scan_videos": "🔍  ভিডিও ফাইল খোঁজা হচ্ছে...",
    "log_found_videos": "✅  {} টি ভিডিও ফাইল পাওয়া গেছে",
    "log_video_done": "  🏁  সম্পন্ন!  ভিডিও: {}  |  ত্রুটি: {}",
    "log_scan_docs": "🔍  নথি খোঁজা হচ্ছে...",
    "log_found_docs": "✅  {} টি নথি পাওয়া গেছে",
    "log_doc_done": "  Word: {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  ত্রুটি: {}",
    "log_skipped": "  ⚠️  {} টি ফোল্ডার বাদ দেওয়া হয়েছে (সিস্টেম/গেম)",
    "log_scan_files": "🔍  ফাইল খোঁজা হচ্ছে...",
    "log_found_files": "✅  {} টি ফাইল পাওয়া গেছে",
    "log_grouping": "⚙️  আকার অনুযায়ী গ্রুপিং...",
    "log_candidates": "  {} টি প্রার্থী যাচাইয়ের জন্য",
    "log_no_dupes": "✅  কোনো ডুপ্লিকেট পাওয়া যায়নি।",
    "log_checksums": "🔐  চেকসাম গণনা হচ্ছে (বড় ফাইলে সময় লাগতে পারে)...",
    "log_scan_complete": "  🏁  স্ক্যান সম্পন্ন!",
    "log_dupe_groups": "  ডুপ্লিকেট গ্রুপ: {}",
    "log_can_save": "  সঞ্চয়:          {}",
    "log_search_in": "🔍  ডুপ্লিকেট খোঁজা হচ্ছে: {}",
    "log_search_folders": "📁  {} টি নির্বাচিত ফোল্ডারে খোঁজা হচ্ছে:",
    "dupe_title": "ডুপ্লিকেট স্ক্যানার – ফলাফল",
    "dupe_header": "🔍  {} ডুপ্লিকেট গ্রুপ  ·  {} অতিরিক্ত কপি  ·  সঞ্চয় {}",
    "dupe_stats": "  {} ফাইল মুছতে চিহ্নিত  ·  {} মুক্ত হবে",
    "dupe_col_file": "ফাইলের নাম",
    "dupe_col_folder": "ফোল্ডার",
    "dupe_col_size": "আকার",
    "dupe_col_date": "তারিখ",
    "dupe_group": "  📁  গ্রুপ {}  –  {} ফাইল  –  সঞ্চয় {}",
    "dupe_btn_del": "🗑  রিসাইকেল বিনে মুছুন",
    "dupe_btn_sel": "☑  সব নির্বাচন করুন",
    "dupe_btn_desel": "☐  সব অনির্বাচন করুন",
    "dupe_ready": "প্রস্তুত",
    "dupe_deleting": "ফাইল মুছে ফেলা হচ্ছে...",
    "dupe_trash_ok": "  ✔  রিসাইকেল বিন: {}",
    "dupe_trash_fail": "  ✘  ত্রুটি: {}",
    "dupe_del_done": "\n  🏁  সম্পন্ন!  মুছে ফেলা: {}  |  ত্রুটি: {}",
    "dupe_done_lbl": "সম্পন্ন!",
    "dupe_none_t": "কিছু নির্বাচিত নয়",
    "dupe_none": "মুছে ফেলার জন্য কোনো ফাইল চিহ্নিত নেই।",
    "dupe_confirm_t": "মুছে ফেলা নিশ্চিত করুন",
    "dupe_confirm": "{} ফাইল রিসাইকেল বিনে যাবে।\n{} মুক্ত হবে।\n\nফাইল পুনরুদ্ধার করা যাবে।\nচালিয়ে যেতে চান?",
    "dupe_no_t": "কোনো ডুপ্লিকেট নেই",
    "dupe_no": "নির্বাচিত এলাকায় কোনো ডুপ্লিকেট পাওয়া যায়নি।",
},

"pt": {
    "lang_btn": "Idioma",
    "app_title": "Organizador de Ficheiros  v{}",
    "app_heading": "📂  Organizador de Ficheiros",
    "app_sub": "Edição USB  v{}  –  Organize fotos, vídeos e documentos",
    "btn_start": "▶  Iniciar",
    "btn_stop": "⏹  Parar",
    "btn_dupes": "🔍  Encontrar duplicados",
    "btn_close": "✖  Fechar",
    "btn_running": "⏳  A executar...",
    "btn_scanning": "⏳  A analisar...",
    "sec_search": "🔎  Onde procurar?",
    "sec_type": "🗂️  O que organizar?",
    "sec_progress": "⏳  Progresso",
    "sec_log": "📋  Registo",
    "search_drive": "  Procurar em toda a unidade",
    "search_folders": "  Escolher pastas específicas",
    "lbl_drive": "💾  Escolher unidade",
    "lbl_folders": "📁  Pastas selecionadas",
    "btn_add": "＋  Adicionar pasta",
    "btn_remove": "✖  Remover seleção",
    "btn_clear": "🗑  Limpar tudo",
    "no_folders": "  Nenhuma pasta selecionada – clique em '＋ Adicionar pasta'",
    "dlg_add_folder": "Escolha uma pasta para pesquisar",
    "type_photos": "📷  Fotos",
    "type_videos": "🎬  Vídeos",
    "type_docs": "📄  Documentos",
    "hint_photos": "→ Unidade:\\Fotos\\Ano\\Mês\\",
    "hint_videos": "→ Unidade:\\Vídeos\\Ano\\Mês\\",
    "hint_docs": "→ Unidade:\\Documentos\\Word|PDF|Excel\\",
    "sort_label": "  Ordenar fotos por:",
    "sort_date": "  📅  Data  –  Ano / Mês",
    "sort_gps": "  🌍  Localização GPS  –  País / Cidade",
    "sort_gps_hint": "     Requer dados GPS na imagem (smartphones guardam automaticamente)",
    "dest_auto": "  Ficheiros serão movidos para: [Unidade:]\\{}\\  (criado automaticamente)",
    "dest_photos": "Fotos",
    "dest_videos": "Videos",
    "dest_docs": "Documentos",
    "dest_gps": "Fotos por localização",
    "dlg_dest": "Escolher pasta de destino",
    "status_ready": "Pronto para começar...",
    "status_done": "Concluído!",
    "status_scan_done": "Análise concluída!",
    "dlg_no_folders_t": "Sem pastas",
    "dlg_no_folders": "Ainda não selecionou nenhuma pasta.\nClique em '+ Adicionar pasta' para selecionar pelo menos uma.",
    "dlg_confirm_t": "Confirmar",
    "dlg_confirm": "Os ficheiros serão MOVIDOS de:\n  {}\n\npara:\n  {}\n\nFez uma cópia de segurança?\nDeseja continuar?",
    "log_no_pillow": "❌  Nem Pillow nem exifread estão instalados!",
    "log_scan_photos": "🔍  A procurar ficheiros de imagem...",
    "log_found_photos": "✅  {} ficheiros de imagem encontrados",
    "log_stopped": "⛔  Parado pelo utilizador.",
    "log_moved_n": "  ✔  {} imagens movidas...",
    "log_err": "  ✘ ERRO: {}: {}",
    "log_done": "  🏁  Concluído!",
    "log_photos_moved": "  Imagens movidas:    {}",
    "log_filedate": "  Data do ficheiro:   {}",
    "log_errors": "  Erros:              {}",
    "log_no_geocoder": "❌  reverse_geocoder não está instalado!",
    "log_install_geo": "   Execute: py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  A procurar imagens com dados GPS...",
    "log_gps_moved": "  Imagens movidas: {}",
    "log_no_gps": "  Sem dados GPS:   {}",
    "log_scan_videos": "🔍  A procurar ficheiros de vídeo...",
    "log_found_videos": "✅  {} ficheiros de vídeo encontrados",
    "log_video_done": "  🏁  Concluído!  Vídeos: {}  |  Erros: {}",
    "log_scan_docs": "🔍  A procurar documentos...",
    "log_found_docs": "✅  {} documentos encontrados",
    "log_doc_done": "  Word: {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  Erros: {}",
    "log_skipped": "  ⚠️  {} pastas ignoradas (sistema/jogos)",
    "log_scan_files": "🔍  A procurar ficheiros...",
    "log_found_files": "✅  {} ficheiros encontrados",
    "log_grouping": "⚙️  A agrupar por tamanho...",
    "log_candidates": "  {} candidatos para verificação",
    "log_no_dupes": "✅  Nenhum duplicado encontrado.",
    "log_checksums": "🔐  A calcular checksums (pode demorar com ficheiros grandes)...",
    "log_scan_complete": "  🏁  Análise concluída!",
    "log_dupe_groups": "  Grupos duplicados: {}",
    "log_can_save": "  Poupança possível: {}",
    "log_search_in": "🔍  A procurar duplicados em: {}",
    "log_search_folders": "📁  A procurar em {} pastas selecionadas:",
    "dupe_title": "Scanner de Duplicados – Resultados",
    "dupe_header": "🔍  {} grupos  ·  {} cópias extra  ·  Poupança {}",
    "dupe_stats": "  {} ficheiros marcados para eliminar  ·  {} será libertado",
    "dupe_col_file": "Ficheiro",
    "dupe_col_folder": "Pasta",
    "dupe_col_size": "Tamanho",
    "dupe_col_date": "Data",
    "dupe_group": "  📁  Grupo {}  –  {} ficheiros  –  poupança {}",
    "dupe_btn_del": "🗑  Eliminar para reciclagem",
    "dupe_btn_sel": "☑  Selecionar todos",
    "dupe_btn_desel": "☐  Desselecionar todos",
    "dupe_ready": "Pronto",
    "dupe_deleting": "A eliminar ficheiros...",
    "dupe_trash_ok": "  ✔  Reciclagem: {}",
    "dupe_trash_fail": "  ✘  Erro: {}",
    "dupe_del_done": "\n  🏁  Concluído!  Eliminados: {}  |  Erros: {}",
    "dupe_done_lbl": "Concluído!",
    "dupe_none_t": "Nada selecionado",
    "dupe_none": "Nenhum ficheiro marcado para eliminação.",
    "dupe_confirm_t": "Confirmar eliminação",
    "dupe_confirm": "{} ficheiros serão movidos para a reciclagem.\nIsto libertará {}.\n\nOs ficheiros podem ser restaurados.\nDeseja continuar?",
    "dupe_no_t": "Sem duplicados",
    "dupe_no": "Nenhum duplicado encontrado na área selecionada.",
},

"ru": {
    "lang_btn": "Язык",
    "app_title": "Органайзер Файлов  v{}",
    "app_heading": "📂  Органайзер Файлов",
    "app_sub": "USB-версия  v{}  –  Организация фото, видео и документов",
    "btn_start": "▶  Начать",
    "btn_stop": "⏹  Стоп",
    "btn_dupes": "🔍  Найти дубликаты",
    "btn_close": "✖  Закрыть",
    "btn_running": "⏳  Выполняется...",
    "btn_scanning": "⏳  Сканирование...",
    "sec_search": "🔎  Где искать?",
    "sec_type": "🗂️  Что организовать?",
    "sec_progress": "⏳  Прогресс",
    "sec_log": "📋  Журнал",
    "search_drive": "  Искать на всём диске",
    "search_folders": "  Выбрать папки",
    "lbl_drive": "💾  Выберите диск",
    "lbl_folders": "📁  Выбранные папки",
    "btn_add": "＋  Добавить папку",
    "btn_remove": "✖  Удалить выбранное",
    "btn_clear": "🗑  Очистить всё",
    "no_folders": "  Папки не выбраны – нажмите '＋ Добавить папку'",
    "dlg_add_folder": "Выберите папку для поиска",
    "type_photos": "📷  Фотографии",
    "type_videos": "🎬  Видео",
    "type_docs": "📄  Документы",
    "hint_photos": "→ Диск:\\Фото\\Год\\Месяц\\",
    "hint_videos": "→ Диск:\\Видео\\Год\\Месяц\\",
    "hint_docs": "→ Диск:\\Документы\\Word|PDF|Excel\\",
    "sort_label": "  Сортировать фото по:",
    "sort_date": "  📅  Дата  –  Год / Месяц",
    "sort_gps": "  🌍  GPS-координаты  –  Страна / Город",
    "sort_gps_hint": "     Требуются GPS-данные в фото (смартфоны сохраняют автоматически)",
    "dest_auto": "  Файлы будут перемещены в: [Диск:]\\{}\\  (создаётся автоматически)",
    "dest_photos": "Photos",
    "dest_videos": "Videos",
    "dest_docs": "Documents",
    "dest_gps": "Photos by location",
    "dlg_dest": "Выберите папку назначения",
    "status_ready": "Готов к запуску...",
    "status_done": "Готово!",
    "status_scan_done": "Сканирование завершено!",
    "dlg_no_folders_t": "Нет папок",
    "dlg_no_folders": "Вы ещё не выбрали папки.\nНажмите '+ Добавить папку'.",
    "dlg_confirm_t": "Подтверждение",
    "dlg_confirm": "Файлы будут ПЕРЕМЕЩЕНЫ из:\n  {}\n\nв:\n  {}\n\nВы сделали резервную копию?\nПродолжить?",
    "log_no_pillow": "❌  Pillow и exifread не установлены!",
    "log_scan_photos": "🔍  Поиск изображений...",
    "log_found_photos": "✅  Найдено {} изображений",
    "log_stopped": "⛔  Остановлено пользователем.",
    "log_moved_n": "  ✔  {} изображений перемещено...",
    "log_err": "  ✘ ОШИБКА: {}: {}",
    "log_done": "  🏁  Готово!",
    "log_photos_moved": "  Перемещено:         {}",
    "log_filedate": "  Дата файла:         {}",
    "log_errors": "  Ошибки:             {}",
    "log_no_geocoder": "❌  reverse_geocoder не установлен!",
    "log_install_geo": "   Выполните: py -m pip install reverse_geocoder",
    "log_scan_gps": "🔍  Поиск изображений с GPS-данными...",
    "log_gps_moved": "  Перемещено:     {}",
    "log_no_gps": "  Без GPS-данных: {}",
    "log_scan_videos": "🔍  Поиск видеофайлов...",
    "log_found_videos": "✅  Найдено {} видеофайлов",
    "log_video_done": "  🏁  Готово!  Видео: {}  |  Ошибки: {}",
    "log_scan_docs": "🔍  Поиск документов...",
    "log_found_docs": "✅  Найдено {} документов",
    "log_doc_done": "  Word: {}  |  PDF: {}  |  Excel: {}",
    "log_doc_errors": "  Ошибки: {}",
    "log_skipped": "  ⚠️  {} папок пропущено (системные/игровые)",
    "log_scan_files": "🔍  Поиск файлов...",
    "log_found_files": "✅  Найдено {} файлов",
    "log_grouping": "⚙️  Группировка по размеру...",
    "log_candidates": "  {} кандидатов для проверки",
    "log_no_dupes": "✅  Дубликаты не найдены.",
    "log_checksums": "🔐  Расчёт контрольных сумм (может занять время для больших файлов)...",
    "log_scan_complete": "  🏁  Сканирование завершено!",
    "log_dupe_groups": "  Групп дубликатов: {}",
    "log_can_save": "  Можно сэкономить: {}",
    "log_search_in": "🔍  Поиск дубликатов в: {}",
    "log_search_folders": "📁  Поиск в {} выбранных папках:",
    "dupe_title": "Сканер Дубликатов – Результаты",
    "dupe_header": "🔍  {} групп  ·  {} доп. копий  ·  Экономия {}",
    "dupe_stats": "  {} файлов отмечено для удаления  ·  {} освободится",
    "dupe_col_file": "Имя файла",
    "dupe_col_folder": "Папка",
    "dupe_col_size": "Размер",
    "dupe_col_date": "Дата",
    "dupe_group": "  📁  Группа {}  –  {} файлов  –  экономия {}",
    "dupe_btn_del": "🗑  Удалить в корзину",
    "dupe_btn_sel": "☑  Выбрать все дубликаты",
    "dupe_btn_desel": "☐  Снять выделение",
    "dupe_ready": "Готов",
    "dupe_deleting": "Удаление файлов...",
    "dupe_trash_ok": "  ✔  Корзина: {}",
    "dupe_trash_fail": "  ✘  Ошибка: {}",
    "dupe_del_done": "\n  🏁  Готово!  Удалено: {}  |  Ошибок: {}",
    "dupe_done_lbl": "Готово!",
    "dupe_none_t": "Ничего не выбрано",
    "dupe_none": "Нет файлов, отмеченных для удаления.",
    "dupe_confirm_t": "Подтвердить удаление",
    "dupe_confirm": "{} файлов будут перемещены в корзину.\nОсвободится {}.\n\nФайлы можно восстановить из корзины.\nПродолжить?",
    "dupe_no_t": "Нет дубликатов",
    "dupe_no": "Дубликаты не найдены в выбранной области.",
},

}  # end TEKSTER
